clear
close

% Compute some useful things about the JDOS generated by CPP code
% João Inácio, 29 Dec. 2020

L = 4;
N_SPINS = L * L;
flatness = 0.9;

exp_f_final_vals = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13];
exp_f_final_vals_2 = [0, 1, 3, 4, 4, 6, 6, 8, 8, 9, 10, 11, 13];
num_f_vals = [4, 7, 10, 13, 16, 19, 21, 24, 27, 30, 33, 36, 39];

JDOS = cell(1000, length(exp_f_final_vals));
JDOS_average = cell(1, length(exp_f_final_vals));
JDOS_sum = cell(1, length(exp_f_final_vals));
data = cell(1000, length(exp_f_final_vals));
run_time = zeros(1000, length(exp_f_final_vals));

tic
parfor idx_exp = 1:length(exp_f_final_vals)
    exp_f_final = exp_f_final_vals(idx_exp);
    exp_f_final_2 = exp_f_final_vals_2(idx_exp);
    num_f = num_f_vals(idx_exp);
    
    
    JDOS_sum{idx_exp} = zeros(N_SPINS + 1);
    JDOS_average{idx_exp} = zeros(N_SPINS + 1);
    
    for run = 1:1000
        file_name_1 = "WL 4L/" + exp_f_final + "/" + run + "_JDOS_2D_" + L + ...
            "L_f" + exp_f_final_2 + "_flatness" + (flatness * 100) + "_WL_CPP.txt";
        JDOS_imported = importdata(file_name_1);
        file_name_2 = "WL 4L/" + exp_f_final + "/" + run + "_JDOS_2D_" + L + ...
            "L_f" + exp_f_final_2 + "_flatness" + (flatness * 100) + "_WL_CPP_data.txt";
        data_imported = importdata(file_name_2);
        
        data{run, idx_exp} = data_imported.data(1:num_f, :);
        run_time(run, idx_exp) = data_imported.data(num_f + 1, 1);
        
        JDOS_imported(:, N_SPINS/2 + 2:end) = 0;
        JDOS_imported(1, N_SPINS + 1) = 1;
        JDOS{run, idx_exp} = JDOS_imported;
        JDOS_sum{idx_exp} = JDOS_sum{idx_exp} + JDOS{run, idx_exp};
    end
    
    JDOS_average{idx_exp} = JDOS_sum{idx_exp} / run;
end
toc

file_name_2 = "WL 4L/" + 1 + "/" + 1 + "_JDOS_2D_" + L + ...
            "L_f" + 0 + "_flatness" + (flatness * 100) + "_WL_CPP_data.txt";
data_imported = importdata(file_name_2);
headers = data_imported.colheaders;

save("Data/JDOS_2D_" + L + "L_flatness" + (flatness * 100) + "_WL_CPP.mat", "JDOS",...
    "JDOS_average", "JDOS_sum", "data", "run_time", "headers")




