clear
close

% Compute some useful things about the JDOS generated by CPP code
% João Inácio, 29 Dec. 2020

L = 4;
N_SPINS = L * L;
skip = N_SPINS;

REP_vals = [1000, 10000, 100000, 1000000];

JDOS = cell(1000, length(REP_vals));
JDOS_average = cell(1, length(REP_vals));
JDOS_sum = cell(1, length(REP_vals));
data = cell(1000, length(REP_vals));
run_time = zeros(1000, length(REP_vals));

tic
parfor idx_REP = 1:length(REP_vals)
    REP = REP_vals(idx_REP);
    
    JDOS_sum{idx_REP} = zeros(N_SPINS + 1);
    JDOS_average{idx_REP} = zeros(N_SPINS + 1);
    
    for run = 1:1000
        file_name_1 = "nRPS 4L/" + REP + "/" + run + "_JDOS_2D_" + L + ...
            "L_10E" + log10(REP) + "_skip" + skip + "_nRPS_CPP.txt";
        JDOS_imported = importdata(file_name_1);
        file_name_2 = "nRPS 4L/" + REP + "/" + run + "_JDOS_2D_" + L + ...
            "L_10E" + log10(REP) + "_skip" + skip + "_nRPS_CPP_data.txt";
        data_imported = importdata(file_name_2);
        
        data{run, idx_REP} = data_imported.data(1:(N_SPINS / 2), :);
        run_time(run, idx_REP) = data_imported.data(N_SPINS/2 + 1, 1);
        
        JDOS{run, idx_REP} = JDOS_imported;
        JDOS_sum{idx_REP} = JDOS_sum{idx_REP} + JDOS_imported;
    end
    
    JDOS_average{idx_REP} = JDOS_sum{idx_REP} / run;
end
toc

headers = data_imported.colheaders;

save("Data/JDOS_2D_" + L + "L_skip" + skip + "_nRPS_CPP.mat", "JDOS",...
    "JDOS_average", "JDOS_sum", "data", "run_time", "headers")




